name: Weekly Storyblok Backup

on:
    schedule:
        - cron: '0 0 * * 0'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Perform Backup
              env:
                  STORYBLOK_OAUTH_TOKEN: ${{ secrets.STORYBLOK_OAUTH_TOKEN }}
                  STORYBLOK_SPACE_ID: ${{ secrets.STORYBLOK_SPACE_ID }}
              run: npx storyblok-backup --token $STORYBLOK_OAUTH_TOKEN --space $STORYBLOK_SPACE_ID

            - name: Delete Old Artifacts
              uses: actions/github-script@v6
              id: artifact
              with:
                  script: |
                      const res = await github.rest.actions.listArtifactsForRepo({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                      })

                      res.data.artifacts
                          .filter(({ name }) => name === 'weekly-backup')
                          .forEach(({ id }) => {
                            github.rest.actions.deleteArtifact({
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                artifact_id: id,
                            })
                          })

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: weekly-backup
                  path: .output
